=== polluks/exult/docs/xml/docs.dtd
<!-- block and inline elements -->

<!ENTITY % inline "#PCDATA|br|em|extref|Exult|kbd|key|q|ref|ref1|section_ref|strong|Studio|Pentagram|img|TM" >

<!ENTITY % lists "ul|ol" >

<!ENTITY % block "cite|configdesc|keytable|para|%lists;" >


<!-- ****************** elements ****************** -->
<!ELEMENT faqs (section*)>
<!ELEMENT readme (section*)>
<!ELEMENT studiodoc (section*)>
<!ELEMENT section (sub*)>
<!ELEMENT sub (header, body)>
<!ELEMENT header (#PCDATA|Exult|Studio|Pentagram)*>
<!ELEMENT body (%block;)*>

<!ELEMENT para ( %inline; )*>
<!ELEMENT cite ( %inline; )*>
<!ELEMENT ol (li)*>
<!ELEMENT ul (li)*>
<!ELEMENT li ( %inline; )*>

<!ELEMENT key (#PCDATA)>
<!ELEMENT kbd (#PCDATA|TM)*>
<!ELEMENT strong (#PCDATA)>
<!ELEMENT em (#PCDATA)*>

<!ELEMENT ref (#PCDATA)>
<!ELEMENT ref1 (#PCDATA)>
<!ELEMENT section_ref (#PCDATA)>
<!ELEMENT extref (#PCDATA)>

<!ELEMENT img (#PCDATA)>

<!ELEMENT q (#PCDATA)>

<!-- Empty elements -->
<!ELEMENT br EMPTY>
<!ELEMENT Exult (#PCDATA)>
<!ELEMENT Studio (#PCDATA)>
<!ELEMENT Pentagram (#PCDATA)>
<!ELEMENT TM (#PCDATA)>

<!ELEMENT configdesc (configtag*)>
<!ELEMENT comment (#PCDATA|ref|key|q|Exult|extref)*>
<!ENTITY % manual "">
<!ELEMENT configtag (#PCDATA|configtag|comment %manual;)*>

<!ELEMENT keytable (keydesc)*>
<!ELEMENT keydesc (#PCDATA)>

<!-- ****************** attributes ****************** -->
<!ATTLIST	faqs		title	CDATA	#REQUIRED>
<!ATTLIST	faqs		changed	CDATA	"">
<!ATTLIST	readme		title	CDATA	#REQUIRED>
<!ATTLIST	readme		changed	CDATA	"">
<!ATTLIST	studiodoc		title	CDATA	#REQUIRED>
<!ATTLIST	studiodoc		changed	CDATA	"">
<!ATTLIST	section		title	CDATA	#REQUIRED>

<!ATTLIST	sub		name	CDATA	"">
<!ATTLIST	cite		name	CDATA	"">
<!ATTLIST	keytable	title	CDATA	#REQUIRED>
<!ATTLIST	keydesc		name	CDATA	"">

<!ATTLIST	ref		target	CDATA	#REQUIRED>
<!ATTLIST	ref1		target	CDATA	#REQUIRED>
<!ATTLIST	section_ref		target	CDATA	#REQUIRED>
<!ATTLIST	extref		target	CDATA	#REQUIRED>
<!ATTLIST	extref		doc	(faq|docs|studio)	#IMPLIED>
<!ATTLIST	img		src 	CDATA	#REQUIRED>
<!ATTLIST	img		alt 	CDATA	#REQUIRED>

<!ATTLIST	configtag	name	CDATA	#REQUIRED>
<!ATTLIST	configtag	manual	(true|false)	#IMPLIED>
<!ATTLIST	configtag	closing-tag (yes|no) "yes">

=== polluks/exult/docs/xml/faq.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE faqs SYSTEM "docs.dtd">
<faqs title="Exult" changed="25 April 2024 (GMT)">
	<section title="Introduction">
		<sub name="exult_version">
			<header>Exult Version</header>
			<body>
				<para>
					These frequently asked questions are for the snapshot version of <Exult/>.
					If you have another <Exult/> version this FAQ can be found where you installed it.
				</para>
			</body>
		</sub>
		<sub name="why_name_exult">
			<header>Why is it called <Exult/> - what is the meaning of this name?</header>
			<body>
				<cite name="Jeff wrote on the Boards">
					I originally wrote it [Exult] solely for X-windows, so that's where
					the 'X' comes from. The "ult", of course, comes from Ultima. It
					was only about 6 months ago [02/29/2000] that I replaced the X code with SDL,
					which is multiplatform. Then Arthuris ported it to Win32 (and to
					BeOS). He had also ported the earlier version, but it was much harder
					to maintain that way.
				</cite>
				<cite name="Ibrahim Holtzmann">
					I'd like to point out that "exult" is also an English verb that
					means "to rejoice, to exhibit great happiness".
				</cite>
			</body>
		</sub>
		<sub name="is_exult_free">
			<header>Is <Exult/> free ?</header>
			<body>
				<para>
					<Exult/> is more than free: it's Free (notice the caps). <Exult/> is released
					under the GNU GPL (General Public License). This means that the source code
					for <Exult/> is freely available and you can do whatever you want with it.
					However, if you make modifications to any of <Exult/>s components and publicly
					redistribute your work you are required to make the source freely available
					in turn. Obviously the <Exult/> team would be very grateful if any
					modifications you make are contributed back to the main code, so that
					everyone can benefit from them. If you want to work on <Exult/> please contact
					us via our
					<extref target="https://github.com/exult/exult/discussions">forum</extref>.<br/>
					More information on the GNU GPL at
					<extref target="https://www.gnu.org/copyleft/gpl.html"/>.
				</para>
			</body>
		</sub>
		<sub name="exult_donation">
			<header>Do you accept donations?</header>
			<body>
				<para>
					No, the <Exult/> team will not accept donations. For us there are greater legal matters
					involved, which none of us particularly want to explore. We do not want to risk the
					wrath of EA for directly profiting off <Exult/>.<br/>
				</para>
			</body>
		</sub>
		<sub name="origin_exult">
			<header>Does Origin or EA support <Exult/>?</header>
			<body>
				<para>
					First of all, Origin has been wiped from existence by EA a long time ago.
					Furthermore, Origin and/or people that worked for Origin have claimed that
					the source code for Ultima VII (BG/SI) has been lost for some time.
					So there is no chance for the <Exult/> team to have a look at the actual code.
				</para>
				<para>
					Also the team tried to contact some people from Origin years ago but received
					neither positive or negative response on the <Exult/> project. So far it seems
					that EA has decided to ignore <Exult/>.
				</para>
				<para>
					On the other hand former Origin employees contacted the team and congratulated
					on their effort. Most noticeable are Lord British himself and Ken Demarest
					(Programming Manager of Ultima VII)(hint:spell his name backwards).
				</para>
			</body>
		</sub>
		<sub name="other_ultimas">
			<header>Will <Exult/> support other Ultima games?</header>
			<body>
				<para>
					<Exult/> supports only Ultima VII (BG/SI and the add-ons). It will never support
					any other Ultima nor do members of the team plan to develop something similar.
					The reasons for this are that no other Ultima is similar to Ultima VII in the
					internal workings and also the team used to be quite sick of reverse engineering
					a game already.
				</para>
			</body>
		</sub>
		<sub name="pentagram">
			<header>But isn't <Pentagram/> some kind of <Exult/> for U8?</header>
			<body>
				<para>
					<Pentagram/> is a pet project by some members of the <Exult/> team (currently mostly
					Willem, Colourless, Fingolfin and Darke). It is a <strong>map and shapes viewer</strong>
					and nothing more (although the team does indeed invest some time to disassemble the Usecode
					of U8). It isn't meant to be something similar to <Exult/>. It is rather a clever plan
					to stir up interest in other coders to carry this basic work further.<br/>
					Any <strong>developer</strong> is welcome to take a look and contact us.
				</para>
				<para>
					After years this plan has come to fruit and <Pentagram/> has been merged into
					<strong>ScummVM</strong>. Even support for the two games <strong>Crusader: No Remorse</strong>
					and <strong>Crusader: No Regret</strong>, which use the same engine, has been progressing
					in <strong>ScummVM</strong>'s code.
				</para>
				<para>
					On the official <Pentagram/> homepage at <extref target="http://pentagram.info/"/>
					you will find more information on this project of before the merge with
					<strong>ScummVM</strong>.
				</para>
			</body>
		</sub>
		<sub name="multiplayer">
			<header>Will there be a multiplayer <Exult/>?</header>
			<body>
				<para>
					No.
				</para>
				<cite name="Jeff on the Forum">
					The question is 'why?'. I continue working on <Exult/>, in large part, because
					nobody makes games like Ultima VII anymore. While I think a multiplayer game
					would be technically interesting, I don't see the need. There are <em>lots</em>
					of them already, and many experienced people working on new ones.
				</cite>
				<para>
					Note however that <Exult/> is open source. If you want a multiplayer Ultima VII no one
					holds you back to code it in.
				</para>
			</body>
		</sub>
		<sub name="whereis_exult">
			<header>Where do I find <Exult/>?</header>
			<body>
				<para>
					The latest official version is found on
					<extref target="https://exult.info/"/><br/>
					The source code of <Exult/> is hosted on GitHub's Git server which you can
					browse and download at <extref target="https://github.com/exult"/>.<br/>
					Daily snapshots of the source code, Windows and macOS binaries can be found at
					<extref target="https://exult.info/download.php"/>.<br/>
					Paulo started a PPA for Ubuntu at
					<extref target="https://launchpad.net/~exult-team/+archive/exult-daily"/>.<br/>
				</para>
				<para>
					To use the PPA for Ubuntu follow these steps in terminal:<br/>
					<kbd>$  sudo apt-add-repository ppa:exult-team/exult-daily</kbd><br/>
					#Adds the repository - you will be required to accept the key file.
					Just press 'Enter'<br/>
					<kbd>$ sudo apt-get update</kbd><br/>
					#Updates your cache.<br/>
					<kbd>$ sudo apt-get install exult exult-audiopack</kbd><br/>
					#Installs Exult itself and audio files
				</para>
			</body>
		</sub>
		<sub name="whatis_snapshot">
			<header>What is a snapshot? Are these screenshots or what?</header>
			<body>
				<para>
					Bugs and not yet implemented features in <Exult/> get fixed almost daily in the code.
					A release is very time consuming that's why there are so few.
				</para>
				<para>
					The snapshot is the newest source code of the program. It is updated every
					night if commits landed in our repository on that day. There is information on how to
					build your own binary in the source but there is also the newest pre-compiled Windows
					and macOS executables.<br/>
					If there is no new one this means that either there were no changes to the code
					or the source failed to compile.
				</para>
			</body>
		</sub>
		<sub name="compile_snapshot">
			<header>How do I compile a source code snapshot for my OS?</header>
			<body>
				<para>
					The source code snapshots contain the files Readme.win32, Readme.MacOSX
					that explain everything. The instructions for Linux systems are
					traditionally in the file called INSTALL.
				</para>
			</body>
		</sub>
		<sub name="latest_version">
			<header>What is the latest version of <Exult/>?</header>
			<body>
				<para>
					The current official release is 1.8.<br/>
					See also <ref target="whereis_exult"/>
					to learn where to get the latest version.
				</para>
				<para>
					To find out which version you are running, press <key>v</key> while in game.
				</para>
				<para>
					At the moment we recommend that people use the latest snapshot rather than
					our last official version since many critical bugs have been fixed since the
					last release.
				</para>
			</body>
		</sub>
		<sub name="what_platforms">
			<header>On what platform does <Exult/> run?</header>
			<body>
				<para>
					<Exult/> should be able to be compiled (with minor modifications) on
					any platform that SDL2 supports. Right now the source can be compiled
					in <strong>Linux, macOS, OpenBSD, FreeBSD,</strong> and
					<strong>Windows (XP/Vista/7, 10, 11)</strong>.
				</para>
				<ul>
					<li><strong>iOS (iPhone and iPad)</strong><br/>
					After initial porting by our member Lanica Dragon, Chaoji Li (aka Litchie)
					successfully ported <Exult/> to iOS. On the iPad <Exult/>  really shines
					and is very enjoyable. However Ultima VII's item management makes it much
					harder to use on the smaller iPhone screens.<br/></li>

					<li><strong>Android, Java</strong><br/>
					Jeff, Dr.Code, is started porting <Exult/> to Android by rewriting it in Java.
					Unfortunately this port has been abandoned but its former progress can be viewed in its
					old	<extref target="https://goo.gl/VJCNG">forum</extref> thread.</li>

					<li><strong>Android, native</strong><br/>
					KenC ported <Exult/> directly to Android, without rewriting it in Java. After a long
					hiatus he continued his work on
					<extref target="https://github.com/ceckak/exult/tree/android-port">Github</extref>,
